apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: credit-card-app
type: Opaque
data:
  rootpassword: SGFpeWFuMTYwOA== # Base64 encoded value of 'Haiyan1608'
  username: Y2NhcHA=  # Base64 encoded value of 'ccapp'
  password: Y2NhcHAxNjA4  # Base64 encoded value of 'ccapp1608'
